# user-service.yml
server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3308/userdb
    username: root
    password: rootPassword

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
